- name: Ensure Apache is deployed 
  hosts: web_servers 
  force_handlers: True 
  gather_facts: no 
  
  roles: 
    # The "my role" role has a dependency 
    # on the "firewall" role. The 
    # "firewall" role requires a 
    # "firewall rules" variable be defined. 
    - role: my_role 
      firewall_rules: 
      
        # Allow http requests from the 
        # internal zone. 
        - zone: internal 
          service: http 
          
        # Add the load balancer IP to 
        # the internal zone. 
        - zone: internal 
          source: 192.168.16.79
