- name: Ensure HAProxy is deployed 
  hosts: lb_servers 
  force_handlers: True 
  gather_facts: no
  
  roles: 
    # The "haproxy" role has a dependency 
    # on the "firewall" role. The 
    # "firewall" rote requires a 
    # "firewall rules" variable be defined. 
    - role: haproxy 
      firewall_rules: 
      # Allow 80/tcp connections 
      - port: 80/tcp
